ALL : list-2-1 list-2-2 list-2-3 list-2-4 list-2-5 list-2-6 list-2-7 list-2-8

list-2-1 : list_2.8.cpp
	g++ -o list-2-1 list_2.1.cpp -std=c++11 -pthread
list-2-2 : list_2.8.cpp
	g++ -o list-2-2 list_2.2.cpp -std=c++11 -pthread
list-2-3 : list_2.8.cpp
	g++ -o list-2-3 list_2.3.cpp -std=c++11 -pthread
list-2-4 : list_2.8.cpp
	g++ -o list-2-4 list_2.4.cpp -std=c++11 -pthread
list-2-5 : list_2.8.cpp
	g++ -o list-2-5 list_2.5.cpp -std=c++11 -pthread
list-2-6 : list_2.8.cpp
	g++ -o list-2-6 list_2.6.cpp -std=c++11 -pthread
list-2-7 : list_2.8.cpp
	g++ -o list-2-7 list_2.7.cpp -std=c++11 -pthread
list-2-8 : list_2.8.cpp
	g++ -o list-2-8 list_2.8.cpp -std=c++11 -pthread
clean: 
	-rm -rf list-2-*
